######################################################################
# Automatically generated by qmake (3.0) ?? 11? 9 14:13:47 2016
######################################################################
QT       += core gui
QT       += network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = UEchoServer
INCLUDEPATH += .

# Input
HEADERS += uechoserver.h
SOURCES += main.cpp uechoserver.cpp
